// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgvlwvbmyxiorsblmmsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZndmx3dmJteXhpb3JzYmxtbXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODcxNjIsImV4cCI6MjA2NjU2MzE2Mn0.vUvUEJUwNu-XE13BCUB97c2n0_ddPlDfuE495D7CJjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);